### PR TITLE
Changes for Dotty compatibility

### PR DESCRIPTION
**Pull request by travisbrown**
I've been publishing this module locally so I can run tests for Cats, etc. on Dotty, and these changes are necessary. This PR doesn't add Dotty cross-building—it just makes some minor adjustments to ensure that the code compiles on both Scala 2 and Dotty.

### CODE REVIEW

**Comment by bvenners** [comment]
@travisbrown Do you mind signing our CLA? I thought we had one from you, but I can't find it. And we want to finally merge this PR.

There are two variants:

http://www.artima.com/cla/contributorsLicenseAgreement.pdf

or for corporate:

http://www.artima.com/cla/corpContributorsLicenseAgreement.pdf

I figure you're the former, but your choice. Please print, sign and scan back a copy to cla@artima.com. We are working on streamlining this with a click-through, but we didn't complete that yet.

Thanks.

Bill

**Comment by travisbrown** [comment]
@bvenners Yes, I thought I'd done this before, but I just sent over a new signed copy. Thanks.

**Comment by cheeseng** [comment]
@travisbrown @bvenners I am working on merging this into scalacheck-1.14/3.2.0.x, and to stage 3.2.0.0 for scalatest 3.2.0 that we are going to release.  Unfortunately, it seems like scalacheck 1.14.3 does not have build/release for Dotty 0.24 currently, if there's one we may build ScalaTest+ScalaCheck 3.2.0.0 for Dotty 0.24 too.

**Comment by travisbrown** [comment]
@cheeseng I've used the ScalaCheck artfacts for Scala 2 in many projects that are cross-built for Dotty via `withDottyCompat`, and have never seen any issues.

**Comment by bvenners** [comment]
@travisbrown Thanks. We received the CLA (and will be sure to keep track of it this time).

**Comment by cheeseng** [comment]
@travisbrown Good to know that it has been working well for you!  Fyi I have staged 3.2.0.0 with dotty 0.24 support (using withDottyCompat as you suggested), and changes in this PR are include in the following PR for 3.2.0.0 release: 

https://github.com/scalatest/scalatestplus-scalacheck/pull/34

**Comment by travisbrown** [comment]
@cheeseng Thanks, looks good to me!

**Comment by cheeseng** [comment]
@travisbrown Closing as this is now included in https://github.com/scalatest/scalatestplus-scalacheck/pull/34 and merged into branch scalacheck-1-14/3.2.0.x .

**Pull request closed without merging**
